package com.billing.invoice.po;

import java.math.BigDecimal;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_DEPT.DEPT_ID
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    private BigDecimal deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_DEPT.DEPT_NAME
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_DEPT.DEPT_ID
     *
     * @return the value of TBL_DEPT.DEPT_ID
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    public BigDecimal getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_DEPT.DEPT_ID
     *
     * @param deptId the value for TBL_DEPT.DEPT_ID
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    public void setDeptId(BigDecimal deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_DEPT.DEPT_NAME
     *
     * @return the value of TBL_DEPT.DEPT_NAME
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_DEPT.DEPT_NAME
     *
     * @param deptName the value for TBL_DEPT.DEPT_NAME
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }
}