package com.billing.invoice.po;

import java.math.BigDecimal;

public class Employee {
	
	
    public Employee() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Employee(BigDecimal empId, String empName, String gender, BigDecimal deptId) {
		super();
		this.empId = empId;
		this.empName = empName;
		this.gender = gender;
		this.deptId = deptId;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMP.EMP_ID
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    private BigDecimal empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMP.EMP_NAME
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMP.GENDER
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMP.DEPT_ID
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    private BigDecimal deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMP.EMP_ID
     *
     * @return the value of TBL_EMP.EMP_ID
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    public BigDecimal getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMP.EMP_ID
     *
     * @param empId the value for TBL_EMP.EMP_ID
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    public void setEmpId(BigDecimal empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMP.EMP_NAME
     *
     * @return the value of TBL_EMP.EMP_NAME
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMP.EMP_NAME
     *
     * @param empName the value for TBL_EMP.EMP_NAME
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMP.GENDER
     *
     * @return the value of TBL_EMP.GENDER
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMP.GENDER
     *
     * @param gender the value for TBL_EMP.GENDER
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMP.DEPT_ID
     *
     * @return the value of TBL_EMP.DEPT_ID
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    public BigDecimal getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMP.DEPT_ID
     *
     * @param deptId the value for TBL_EMP.DEPT_ID
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    public void setDeptId(BigDecimal deptId) {
        this.deptId = deptId;
    }
}