package com.billing.invoice.dao;

import com.billing.invoice.po.Department;
import com.billing.invoice.po.DepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_DEPT
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    long countByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_DEPT
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    int deleteByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_DEPT
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_DEPT
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_DEPT
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    List<Department> selectByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_DEPT
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_DEPT
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Department record, @Param("example") DepartmentExample example);
}