package com.billing.invoice.dao;

import com.billing.invoice.po.Employee;
import com.billing.invoice.po.EmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMP
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    long countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMP
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMP
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMP
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMP
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMP
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMP
     *
     * @mbg.generated Sun Jan 06 01:54:02 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);
}